services:
  cpa-plus:
    image: ${CPA_PLUS_IMAGE:-6enta0/cpaplus:latest}
    pull_policy: always
    container_name: cpa-plus
    environment:
      DEPLOY: ${DEPLOY:-}
    ports:
      - "${CPA_PORT:-8317}:8317"
    volumes:
      - ${CPA_CONFIG_PATH:-./config.yaml}:/CLIProxyAPI/config.yaml
      - ${CPA_AUTH_PATH:-./auths}:/root/.cli-proxy-api
      - ${CPA_LOG_PATH:-./logs}:/CLIProxyAPI/logs
      - cpa-data:/CLIProxyAPI/data
    restart: unless-stopped

volumes:
  cpa-data:
